# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mganik_airflow_docs',
                'doc_host': 'https://entrefine.github.io',
                'git_url': 'https://github.com/entrefine/mganik_airflow_docs',
                'lib_path': 'mganik_airflow_docs'},
  'syms': {'mganik_airflow_docs.core': {'mganik_airflow_docs.core.foo': ('dbt_docs.html#foo', 'mganik_airflow_docs/core.py')}}}
